#include <stdio.h>
#include <math.h>

#include "io.h"

////////////////////////////////////////////////
// Binary I/O functions
////////////////////////////////////////////////

// print binary header
void
io_binary_print_header (binary_header_class * binary_header)
{
  // print signature (only first 3 characters)
  printf ("Header signature validated (%c%c%c)\n",
	  binary_header->signature[0], binary_header->signature[1],
	  binary_header->signature[2]);

  printf ("Generated by QOMET v%d.%d.%d (revision %d)\n",
	  binary_header->major_version, binary_header->minor_version,
	  binary_header->subminor_version, binary_header->svn_revision);
  printf ("Number of nodes: %d\n", binary_header->node_number);
  printf ("Number of time records: %ld\n", binary_header->time_record_number);
}

// print binary time record
void
io_binary_print_time_record (binary_time_record_class * binary_time_record)
{
  printf ("- Time: %.2f s (%d records)\n", binary_time_record->time,
	  binary_time_record->record_number);
}

// print binary record
void
io_binary_print_record (binary_record_class * binary_record)
{
  printf ("-- Record: from_node=%d to_node=%d FER=%.4f num_retr=%.4f \
op_rate=%.2f bandwidth=%.2f loss_rate=%.4f delay=%.4f\n", binary_record->from_node, 
	  binary_record->to_node, binary_record->frame_error_rate, 
	  binary_record->num_retransmissions, binary_record->operating_rate, 
	  binary_record->bandwidth, binary_record->loss_rate, binary_record->delay);
}

// copy binary record
void
io_binary_copy_record (binary_record_class * binary_record_dst,
		       binary_record_class * binary_record_src)
{
  binary_record_dst->from_node = binary_record_src->from_node;
  binary_record_dst->to_node = binary_record_src->to_node;
  binary_record_dst->frame_error_rate = binary_record_src->frame_error_rate;
  binary_record_dst->num_retransmissions =
    binary_record_src->num_retransmissions;
  binary_record_dst->operating_rate = binary_record_src->operating_rate;
  binary_record_dst->bandwidth = binary_record_src->bandwidth;
  binary_record_dst->loss_rate = binary_record_src->loss_rate;
  binary_record_dst->delay = binary_record_src->delay;
}

// read header of QOMET binary output file;
// return SUCCESS on succes, ERROR on error
int
io_read_binary_header_from_file (binary_header_class * binary_header,
				 FILE * binary_input_file)
{
  // read header from file
  if (fread (binary_header, sizeof (binary_header_class),
	     1, binary_input_file) != 1)
    {
      printf ("Error reading binary header from file");
      perror ("fread");
      return ERROR;
    }

  // check signature (DEFINE SOMEWHERE IN HEADER FILE...)
  if (!(binary_header->signature[0] == 'Q' &&
	binary_header->signature[1] == 'M' &&
	binary_header->signature[2] == 'T' &&
	binary_header->signature[3] == '\0'))
    {
      printf ("Incorrect signature in binary file");
      return ERROR;
    }

  return SUCCESS;
}

// write header of QOMET binary output file;
// return SUCCESS on succes, ERROR on error
int
io_write_binary_header_to_file (int node_number, long int time_record_number,
				int major_version,
				int minor_version,
				int subminor_version,
				int svn_revision, FILE * binary_file)
{
  binary_header_class binary_header;

  binary_header.signature[0] = 'Q';
  binary_header.signature[1] = 'M';
  binary_header.signature[2] = 'T';
  binary_header.signature[3] = '\0';

  binary_header.major_version = major_version;
  binary_header.minor_version = minor_version;
  binary_header.subminor_version = subminor_version;
  binary_header.svn_revision = svn_revision;

  binary_header.node_number = node_number;
  binary_header.time_record_number = time_record_number;

  // write header to file
  if (fwrite (&binary_header, sizeof (binary_header_class),
	      1, binary_file) != 1)
    {
      printf ("Error writing binary output header to file");
      perror ("fwrite");
      return ERROR;
    }

  return SUCCESS;
}

// read a time record of QOMET binary output file;
// return SUCCESS on succes, ERROR on error
int
io_read_binary_time_record_from_file (binary_time_record_class *
				      binary_time_record,
				      FILE * binary_input_file)
{
  // read time record from file
  if (fread (binary_time_record, sizeof (binary_time_record_class),
	     1, binary_input_file) != 1)
    {
      printf ("Error reading binary time record from file");
      perror ("fread");
      return ERROR;
    }

  return SUCCESS;
}

// directly write a time record of QOMET binary output file;
// return SUCCESS on succes, ERROR on error
int
io_write_binary_time_record_to_file2 (binary_time_record_class *
				      binary_time_record, FILE * binary_file)
{
  // write time record to file
  if (fwrite (binary_time_record,
	      sizeof (binary_time_record_class), 1, binary_file) != 1)
    {
      printf ("Error writing binary output time record to file");
      perror ("fwrite");
      return ERROR;
    }

  return SUCCESS;
}

// read a record of QOMET binary output file;
// return SUCCESS on succes, ERROR on error
int
io_read_binary_record_from_file (binary_record_class * binary_record,
				 FILE * binary_input_file)
{
  // record from file
  if (fread (binary_record, sizeof (binary_record_class),
	     1, binary_input_file) != 1)
    {
      printf ("Error reading binary record from file");
      perror ("fread");
      return ERROR;
    }

  return SUCCESS;
}

// read 'number_records' records from a QOMET binary output file;
// return SUCCESS on succes, ERROR on error
int
io_read_binary_records_from_file (binary_record_class * binary_records,
				  int number_records,
				  FILE * binary_input_file)
{
  // records from file
  //printf("Reading %d records from file\n", number_records);
  //fflush(stdout);

  if (fread (binary_records, sizeof (binary_record_class),
	     number_records, binary_input_file) != number_records)
    {
      printf ("Error reading binary records from file");
      perror ("fread");
      return ERROR;
    }

  return SUCCESS;
}


// directly write a record of QOMET binary output file;
// return SUCCESS on succes, ERROR on error
int
io_write_binary_record_to_file2 (binary_record_class * binary_record,
				 FILE * binary_file)
{
  //////////////////////////////////////////////////////////////////
  // NOTE: WHEN MORE FIELDS WILL BE ADDED, TAKE CARE TO CONVERT
  // X & Y COORDINATES TO LAT & LONG IF CARTESIAN SYSTEM IS NOT USED
  //////////////////////////////////////////////////////////////////

  // write record to file
  if (fwrite (binary_record, sizeof (binary_record_class),
	      1, binary_file) != 1)
    {
      printf ("Error writing binary output record to file");
      perror ("fwrite");
      return ERROR;
    }

  return SUCCESS;
}
